### PR TITLE
Changing XAML editor to use Monaco editor 

### PR DESCRIPTION
**Pull request by nickrandolph**
GitHub Issue (If applicable): #139

## PR Type

What kind of change does this PR introduce?
- Feature

## What is the current behavior?
XAML editor is simple textbox

## What is the new behavior?
XAML editor uses the Monaco editor which can provide intellisense and code highlighting

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [ ] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by nickrandolph** [comment]
@carldebilly let me know what you think.

**Comment by nickrandolph** [comment]
@carldebilly I've fixed up the Uno.Monaco.Editor nuget package so we don't need to include all the monaco source files here (or anywhere else that wants to use the Monaco Editor)

**Comment by nickrandolph** [comment]
GifMaker_20200709091440396
@carldebilly / @jeromelaban I've update the playground to include basic intellisense and error highlighting (see attached gif)

**Comment by MelbourneDeveloper** [comment]
@nickrandolph amazing!

**Comment by jeromelaban** [comment]
@nickrandolph loving this !!Very nice work :)

**Comment by CyborgDE** [comment]
Is not working in the current version :-(
https://playground.platform.uno/

I figured out, I have to desantize the result :
var registerCompletionItemProvider = (languageId, characters) =>
    monaco.languages.registerCompletionItemProvider(languageId,
        {
            triggerCharacters: characters,
            provideCompletionItems: (model, position, context, token) => callParentEventAsync(
                "CompletionItemProvider" + languageId,
                [JSON.stringify(position), JSON.stringify(context)]).then(result => {
                if (result) {
                    return JSON.parse(desantize(result));
                }
                return null;
            }),
            resolveCompletionItem: (item, token) => callParentEventAsync("CompletionItemRequested" + languageId,
                [JSON.stringify(item)]).then(result => {
                if (result) {
                    return JSON.parse(desantize(result));
                }
                return null;
            })
        });

**Pull request merged**
